"""
evidence/database.py

All SQLite operations for Payload Capture Suite.

Keeps database code completely separate from UI and capture logic.
The rest of the application calls the functions here; nothing else
should open raw sqlite3 connections.
"""

import sqlite3
import pathlib
import datetime

# Database file lives inside the project data/ directory
import sys as _sys

def _get_base_dir() -> pathlib.Path:
    """Return the data directory root — works both frozen (exe) and from source."""
    if getattr(_sys, "frozen", False):
        return pathlib.Path(_sys.executable).parent
    return pathlib.Path(__file__).parent.parent

DB_PATH = _get_base_dir() / "data" / "payloadcapture.db"


# ─── Connection helper ───────────────────────────────────────────────────────

def get_connection() -> sqlite3.Connection:
    """
    Open a database connection.

    We set row_factory so every row comes back as a dict-like object,
    which is much easier to work with than plain tuples.
    """
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")   # better concurrent access
    return conn


# ─── Schema creation ─────────────────────────────────────────────────────────

def initialise_database() -> None:
    """
    Create all tables if they do not already exist.
    Safe to call every time the application starts.
    """
    conn = get_connection()
    cursor = conn.cursor()

    # Sessions — one row per investigation session
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sessions (
            session_id    TEXT PRIMARY KEY,
            created_at    TEXT NOT NULL,
            closed_at     TEXT,
            interface     TEXT,
            capture_mode  TEXT DEFAULT 'LIVE',
            analyst       TEXT DEFAULT 'Analyst',
            description   TEXT,
            total_packets INTEGER DEFAULT 0,
            total_bytes   INTEGER DEFAULT 0,
            total_flows   INTEGER DEFAULT 0,
            total_alerts  INTEGER DEFAULT 0
        )
    """)

    # Packets — one row per captured packet
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS packets (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            packet_number INTEGER NOT NULL,
            capture_time  TEXT NOT NULL,
            direction     TEXT,
            protocol      TEXT,
            src_ip        TEXT,
            src_port      INTEGER,
            dst_ip        TEXT,
            dst_port      INTEGER,
            packet_size   INTEGER DEFAULT 0,
            payload_size  INTEGER DEFAULT 0,
            risk_level    TEXT DEFAULT 'NONE',
            flow_id       TEXT,
            raw_summary   TEXT,
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    # Flows — grouped conversations between two endpoints
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS flows (
            flow_id       TEXT PRIMARY KEY,
            session_id    TEXT NOT NULL,
            protocol      TEXT,
            src_ip        TEXT,
            src_port      INTEGER,
            dst_ip        TEXT,
            dst_port      INTEGER,
            packet_count  INTEGER DEFAULT 0,
            byte_count    INTEGER DEFAULT 0,
            first_seen    TEXT,
            last_seen     TEXT,
            direction     TEXT DEFAULT 'UNKNOWN',
            risk_level    TEXT DEFAULT 'NONE',
            status        TEXT DEFAULT 'ACTIVE',
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    # Alerts — generated by the rule engine
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            created_at    TEXT NOT NULL,
            severity      TEXT NOT NULL,
            title         TEXT NOT NULL,
            description   TEXT,
            evidence      TEXT,
            recommendation TEXT,
            related_ip    TEXT,
            related_flow  TEXT,
            reviewed      INTEGER DEFAULT 0,
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    # Findings — analyst-confirmed conclusions (different from auto-alerts)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS findings (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            created_at    TEXT NOT NULL,
            severity      TEXT NOT NULL,
            title         TEXT NOT NULL,
            description   TEXT,
            evidence      TEXT,
            state         TEXT DEFAULT 'NEW',
            analyst_note  TEXT,
            updated_at    TEXT,
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    # Action / audit log
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS action_log (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            logged_at     TEXT NOT NULL,
            action        TEXT NOT NULL,
            detail        TEXT,
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    # Analyst notes — attached to any object in the investigation
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS notes (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            created_at    TEXT NOT NULL,
            target_type   TEXT,
            target_id     TEXT,
            content       TEXT NOT NULL,
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    # IP address metadata — observed in the session
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS ip_addresses (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            address       TEXT NOT NULL,
            ip_type       TEXT,
            reverse_dns   TEXT,
            packet_count  INTEGER DEFAULT 0,
            byte_count    INTEGER DEFAULT 0,
            flow_count    INTEGER DEFAULT 0,
            first_seen    TEXT,
            last_seen     TEXT,
            UNIQUE(session_id, address)
        )
    """)

    # Timeline events — significant network events in order
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS timeline_events (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            event_time    TEXT NOT NULL,
            event_type    TEXT NOT NULL,
            description   TEXT,
            related_ip    TEXT,
            related_flow  TEXT,
            related_packet INTEGER,
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    # Evidence files — exported artifacts with their hashes
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS evidence_files (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id    TEXT NOT NULL,
            created_at    TEXT NOT NULL,
            filename      TEXT NOT NULL,
            file_path     TEXT NOT NULL,
            file_type     TEXT,
            sha256        TEXT,
            FOREIGN KEY (session_id) REFERENCES sessions(session_id)
        )
    """)

    conn.commit()
    conn.close()


# ─── Session functions ────────────────────────────────────────────────────────

def create_session(session_id: str, interface: str = "", analyst: str = "Analyst") -> None:
    """Insert a new session row."""
    now = datetime.datetime.now().isoformat(timespec="seconds")
    conn = get_connection()
    conn.execute(
        """
        INSERT INTO sessions (session_id, created_at, interface, analyst)
        VALUES (?, ?, ?, ?)
        """,
        (session_id, now, interface, analyst)
    )
    conn.commit()
    conn.close()


def close_session(session_id: str) -> None:
    """Mark a session as closed."""
    now = datetime.datetime.now().isoformat(timespec="seconds")
    conn = get_connection()
    conn.execute(
        "UPDATE sessions SET closed_at = ? WHERE session_id = ?",
        (now, session_id)
    )
    conn.commit()
    conn.close()


def get_all_sessions() -> list:
    """Return all sessions, newest first."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM sessions ORDER BY created_at DESC"
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_session(session_id: str) -> dict | None:
    """Return a single session by ID."""
    conn = get_connection()
    row = conn.execute(
        "SELECT * FROM sessions WHERE session_id = ?", (session_id,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None


def update_session_stats(session_id: str, packets: int, bytes_: int,
                         flows: int, alerts: int) -> None:
    """Update the rolling counters on a session."""
    conn = get_connection()
    conn.execute(
        """
        UPDATE sessions
        SET total_packets = ?, total_bytes = ?, total_flows = ?, total_alerts = ?
        WHERE session_id = ?
        """,
        (packets, bytes_, flows, alerts, session_id)
    )
    conn.commit()
    conn.close()


def delete_session(session_id: str) -> None:
    """
    Permanently delete a session and all its associated data.
    The caller must confirm with the user before calling this.
    """
    conn = get_connection()
    # Delete child rows first (foreign key constraints)
    for table in ["packets", "flows", "alerts", "findings", "notes",
                  "ip_addresses", "timeline_events", "evidence_files"]:
        conn.execute(f"DELETE FROM {table} WHERE session_id = ?", (session_id,))
    conn.execute("DELETE FROM sessions WHERE session_id = ?", (session_id,))
    conn.commit()
    conn.close()


# ─── Packet functions ─────────────────────────────────────────────────────────

def insert_packet(session_id: str, packet_data: dict) -> None:
    """
    Insert a single parsed packet record.
    packet_data keys match the packets table columns.
    """
    conn = get_connection()
    conn.execute(
        """
        INSERT INTO packets
            (session_id, packet_number, capture_time, direction, protocol,
             src_ip, src_port, dst_ip, dst_port, packet_size, payload_size,
             risk_level, flow_id, raw_summary)
        VALUES
            (:session_id, :packet_number, :capture_time, :direction, :protocol,
             :src_ip, :src_port, :dst_ip, :dst_port, :packet_size, :payload_size,
             :risk_level, :flow_id, :raw_summary)
        """,
        {**packet_data, "session_id": session_id}
    )
    conn.commit()
    conn.close()


def insert_packets_bulk(session_id: str, packet_list: list[dict]) -> None:
    """
    Insert many packets at once — much faster than one INSERT per packet.
    Used during bulk saves or PCAP import.
    """
    if not packet_list:
        return
    conn = get_connection()
    conn.executemany(
        """
        INSERT INTO packets
            (session_id, packet_number, capture_time, direction, protocol,
             src_ip, src_port, dst_ip, dst_port, packet_size, payload_size,
             risk_level, flow_id, raw_summary)
        VALUES
            (:session_id, :packet_number, :capture_time, :direction, :protocol,
             :src_ip, :src_port, :dst_ip, :dst_port, :packet_size, :payload_size,
             :risk_level, :flow_id, :raw_summary)
        """,
        [{**p, "session_id": session_id} for p in packet_list]
    )
    conn.commit()
    conn.close()


def get_packets(session_id: str, limit: int = 10000) -> list:
    """Return packets for a session, newest first, up to limit."""
    conn = get_connection()
    rows = conn.execute(
        """
        SELECT * FROM packets
        WHERE session_id = ?
        ORDER BY packet_number ASC
        LIMIT ?
        """,
        (session_id, limit)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ─── Flow functions ───────────────────────────────────────────────────────────

def upsert_flow(session_id: str, flow: dict) -> None:
    """
    Insert or update a flow record.
    flow_id is the natural key — a tuple of (src_ip, src_port, dst_ip, dst_port, protocol).
    """
    conn = get_connection()
    conn.execute(
        """
        INSERT INTO flows
            (flow_id, session_id, protocol, src_ip, src_port, dst_ip, dst_port,
             packet_count, byte_count, first_seen, last_seen, direction, risk_level)
        VALUES
            (:flow_id, :session_id, :protocol, :src_ip, :src_port, :dst_ip, :dst_port,
             :packet_count, :byte_count, :first_seen, :last_seen, :direction, :risk_level)
        ON CONFLICT(flow_id) DO UPDATE SET
            packet_count = excluded.packet_count,
            byte_count   = excluded.byte_count,
            last_seen    = excluded.last_seen,
            risk_level   = excluded.risk_level
        """,
        {**flow, "session_id": session_id}
    )
    conn.commit()
    conn.close()


def get_flows(session_id: str) -> list:
    """Return all flows for a session."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM flows WHERE session_id = ? ORDER BY packet_count DESC",
        (session_id,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ─── Alert functions ──────────────────────────────────────────────────────────

def insert_alert(session_id: str, alert: dict) -> int:
    """Insert an alert generated by the rule engine. Returns the new row ID."""
    now = datetime.datetime.now().isoformat(timespec="seconds")
    conn = get_connection()
    cursor = conn.execute(
        """
        INSERT INTO alerts
            (session_id, created_at, severity, title, description,
             evidence, recommendation, related_ip, related_flow)
        VALUES
            (:session_id, :created_at, :severity, :title, :description,
             :evidence, :recommendation, :related_ip, :related_flow)
        """,
        {**alert, "session_id": session_id, "created_at": now}
    )
    conn.commit()
    row_id = cursor.lastrowid
    conn.close()
    return row_id


def get_alerts(session_id: str) -> list:
    """Return all alerts for a session, most recent first."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM alerts WHERE session_id = ? ORDER BY created_at DESC",
        (session_id,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ─── Note functions ───────────────────────────────────────────────────────────

def insert_note(session_id: str, target_type: str, target_id: str, content: str) -> None:
    """Attach an analyst note to any object in the investigation."""
    now = datetime.datetime.now().isoformat(timespec="seconds")
    conn = get_connection()
    conn.execute(
        """
        INSERT INTO notes (session_id, created_at, target_type, target_id, content)
        VALUES (?, ?, ?, ?, ?)
        """,
        (session_id, now, target_type, target_id, content)
    )
    conn.commit()
    conn.close()


def get_notes(session_id: str, target_type: str = None, target_id: str = None) -> list:
    """Return notes for a session, optionally filtered by object."""
    conn = get_connection()
    if target_type and target_id:
        rows = conn.execute(
            """
            SELECT * FROM notes
            WHERE session_id = ? AND target_type = ? AND target_id = ?
            ORDER BY created_at ASC
            """,
            (session_id, target_type, target_id)
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT * FROM notes WHERE session_id = ? ORDER BY created_at ASC",
            (session_id,)
        ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ─── Statistics helper ────────────────────────────────────────────────────────

def get_session_statistics(session_id: str) -> dict:
    """
    Calculate aggregate statistics for a session.
    Returns a dict the UI and report builder can display directly.
    """
    conn = get_connection()

    # Basic totals
    totals = conn.execute(
        """
        SELECT
            COUNT(*)                          AS total_packets,
            COALESCE(SUM(packet_size), 0)     AS total_bytes,
            COALESCE(SUM(payload_size), 0)    AS total_payload_bytes
        FROM packets
        WHERE session_id = ?
        """,
        (session_id,)
    ).fetchone()

    # Protocol distribution
    proto_rows = conn.execute(
        """
        SELECT protocol, COUNT(*) AS count
        FROM packets
        WHERE session_id = ?
        GROUP BY protocol
        ORDER BY count DESC
        """,
        (session_id,)
    ).fetchall()

    # Top source IPs
    top_src = conn.execute(
        """
        SELECT src_ip, COUNT(*) AS count
        FROM packets
        WHERE session_id = ? AND src_ip IS NOT NULL
        GROUP BY src_ip
        ORDER BY count DESC
        LIMIT 10
        """,
        (session_id,)
    ).fetchall()

    # Top destination IPs
    top_dst = conn.execute(
        """
        SELECT dst_ip, COUNT(*) AS count
        FROM packets
        WHERE session_id = ? AND dst_ip IS NOT NULL
        GROUP BY dst_ip
        ORDER BY count DESC
        LIMIT 10
        """,
        (session_id,)
    ).fetchall()

    # Flow count
    flow_count = conn.execute(
        "SELECT COUNT(*) FROM flows WHERE session_id = ?", (session_id,)
    ).fetchone()[0]

    # Alert count
    alert_count = conn.execute(
        "SELECT COUNT(*) FROM alerts WHERE session_id = ?", (session_id,)
    ).fetchone()[0]

    conn.close()

    return {
        "total_packets":       totals["total_packets"],
        "total_bytes":         totals["total_bytes"],
        "total_payload_bytes": totals["total_payload_bytes"],
        "total_flows":         flow_count,
        "total_alerts":        alert_count,
        "protocol_distribution": [dict(r) for r in proto_rows],
        "top_sources":           [dict(r) for r in top_src],
        "top_destinations":      [dict(r) for r in top_dst],
    }


# ─── Finding state management ─────────────────────────────────────────────────

def update_finding_state(finding_id: int, state: str,
                          analyst_note: str = "") -> None:
    """Update the lifecycle state of a finding."""
    import datetime
    now = datetime.datetime.now().isoformat(timespec="seconds")
    conn = get_connection()
    conn.execute(
        "UPDATE findings SET state=?, analyst_note=?, updated_at=? WHERE id=?",
        (state, analyst_note, now, finding_id)
    )
    conn.commit()
    conn.close()


def get_findings(session_id: str) -> list:
    """Return all findings for a session, ordered by severity."""
    conn = get_connection()
    severity_order = "CASE severity WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 WHEN 'LOW' THEN 3 ELSE 4 END"
    rows = conn.execute(
        f"SELECT * FROM findings WHERE session_id=? ORDER BY {severity_order}, created_at DESC",
        (session_id,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ─── Action log ───────────────────────────────────────────────────────────────

def log_action(session_id: str, action: str, detail: str = "") -> None:
    """Append an entry to the investigation audit trail."""
    import datetime
    now = datetime.datetime.now().isoformat(timespec="seconds")
    conn = get_connection()
    conn.execute(
        "INSERT INTO action_log (session_id, logged_at, action, detail) VALUES (?,?,?,?)",
        (session_id, now, action, detail)
    )
    conn.commit()
    conn.close()


def get_action_log(session_id: str) -> list:
    """Return all audit trail entries for a session."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM action_log WHERE session_id=? ORDER BY logged_at ASC",
        (session_id,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ─── Global search ────────────────────────────────────────────────────────────

def global_search(session_id: str, query: str, limit: int = 200) -> dict:
    """
    Search across packets, flows, findings, notes, and timeline events
    for a session. Returns a dict with results per category.

    Uses SQLite LIKE for broad matching — fast for typical analyst queries.
    """
    q = f"%{query}%"
    conn = get_connection()

    packets = conn.execute(
        """SELECT packet_number, capture_time, protocol, src_ip, dst_ip,
                  src_port, dst_port, risk_level
           FROM packets
           WHERE session_id=?
             AND (src_ip LIKE ? OR dst_ip LIKE ? OR protocol LIKE ?
                  OR CAST(src_port AS TEXT) LIKE ? OR CAST(dst_port AS TEXT) LIKE ?)
           ORDER BY packet_number ASC LIMIT ?""",
        (session_id, q, q, q, q, q, limit)
    ).fetchall()

    flows = conn.execute(
        """SELECT flow_id, protocol, src_ip, src_port, dst_ip, dst_port,
                  packet_count, byte_count, risk_level
           FROM flows
           WHERE session_id=?
             AND (src_ip LIKE ? OR dst_ip LIKE ? OR protocol LIKE ?
                  OR CAST(src_port AS TEXT) LIKE ? OR CAST(dst_port AS TEXT) LIKE ?)
           LIMIT ?""",
        (session_id, q, q, q, q, q, limit)
    ).fetchall()

    findings = conn.execute(
        """SELECT id, severity, title, description, state
           FROM findings
           WHERE session_id=?
             AND (title LIKE ? OR description LIKE ? OR evidence LIKE ?)
           LIMIT ?""",
        (session_id, q, q, q, limit)
    ).fetchall()

    notes = conn.execute(
        """SELECT id, created_at, target_type, target_id, content
           FROM notes
           WHERE session_id=? AND content LIKE ?
           LIMIT ?""",
        (session_id, q, limit)
    ).fetchall()

    timeline = conn.execute(
        """SELECT id, event_time, event_type, description
           FROM timeline_events
           WHERE session_id=? AND description LIKE ?
           LIMIT ?""",
        (session_id, q, limit)
    ).fetchall()

    conn.close()

    return {
        "query":    query,
        "packets":  [dict(r) for r in packets],
        "flows":    [dict(r) for r in flows],
        "findings": [dict(r) for r in findings],
        "notes":    [dict(r) for r in notes],
        "timeline": [dict(r) for r in timeline],
    }
