"""
ui/alerts_window.py

Alerts & Findings window.

Displays findings generated by the local rule engine.

Design principles:
  - Never say "THIS IS MALICIOUS". Findings are observations.
  - Every finding shows the evidence that triggered it.
  - Every finding includes a concrete recommendation.
  - Severity reflects priority for investigation, not certainty of threat.
  - The analyst reviews and decides; the application does not decide for them.
"""

import tkinter as tk
from tkinter import ttk, messagebox
import datetime

from config.theme import (
    BG_DARK, BG_CARD, BG_INPUT, BG_SELECTED,
    FG_PRIMARY, FG_SECONDARY, FG_ACCENT, FG_SUCCESS,
    FG_WARNING, FG_INFO, FG_MUTED,
    FONT_BODY, FONT_LABEL, FONT_CARD_TITLE, FONT_SMALL, PAD_OUTER, PAD_INNER, PAD_SMALL, PAD_TINY,
    ALERT_WINDOW_SIZE, SEVERITY_COLORS,
)
from ui.widgets import (
    DarkButton, StatusBar, horizontal_separator,
    section_header,
)
from analysis.rules import run_all_rules, severity_sort_key
from evidence.database import insert_alert, insert_note, update_finding_state, log_action


# Severity display order (most severe first)
SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


class AlertsWindow:
    """
    Alerts & Findings workstation.

    Parameters
    ----------
    parent     : Tk root window
    session_id : active session ID
    packets    : list of parsed packet dicts
    flows      : list of flow dicts
    """

    def __init__(self, parent: tk.Tk, session_id: str,
                 packets: list[dict], flows: list[dict]):
        self.parent     = parent
        self.session_id = session_id
        self._packets   = packets
        self._flows     = flows

        # All findings (generated + loaded from DB)
        self._findings: list[dict] = []

        self.window = tk.Toplevel(parent)
        self.window.title("Alerts & Findings")
        self.window.geometry(ALERT_WINDOW_SIZE)
        self.window.configure(bg=BG_DARK)
        self.window.protocol("WM_DELETE_WINDOW", self.window.destroy)

        self._build_ui()
        self._run_analysis()

    # ── UI Construction ───────────────────────────────────────────────────────

    def _build_ui(self) -> None:
        self._build_header()
        horizontal_separator(self.window).pack(fill="x")

        body = tk.Frame(self.window, bg=BG_DARK)
        body.pack(fill="both", expand=True)

        self._build_findings_list(body)
        self._build_detail_panel(body)

        self._status_bar = StatusBar(self.window)
        self._status_bar.pack(side="bottom", fill="x")

    def _build_header(self) -> None:
        header = tk.Frame(self.window, bg=BG_CARD, pady=PAD_SMALL, padx=PAD_OUTER)
        header.pack(fill="x")

        left = tk.Frame(header, bg=BG_CARD)
        left.pack(side="left")

        tk.Label(left, text="ALERTS & FINDINGS", bg=BG_CARD,
                 fg=FG_ACCENT, font=FONT_CARD_TITLE).pack(anchor="w")
        tk.Label(
            left,
            text="Heuristic findings — observations requiring analyst review, not automatic verdicts",
            bg=BG_CARD, fg=FG_SECONDARY, font=FONT_SMALL
        ).pack(anchor="w")

        right = tk.Frame(header, bg=BG_CARD)
        right.pack(side="right")

        DarkButton(right, "RE-ANALYSE", command=self._run_analysis,
                   accent=True).pack(side="right", padx=2)
        DarkButton(right, "SAVE TO SESSION",
                   command=self._save_to_session).pack(side="right", padx=2)
        DarkButton(right, "EXPORT CSV",
                   command=self._export_csv).pack(side="right", padx=2)

        # Severity filter bar
        filter_row = tk.Frame(header, bg=BG_CARD)
        filter_row.pack(fill="x", pady=(PAD_SMALL, 0))

        tk.Label(filter_row, text="FILTER:", bg=BG_CARD,
                 fg=FG_SECONDARY, font=FONT_LABEL).pack(side="left")

        self._sev_filter = tk.StringVar(value="ALL")
        self._sev_buttons: dict[str, tk.Button] = {}

        for label in ["ALL"] + SEVERITY_ORDER:
            color = SEVERITY_COLORS.get(label, FG_SECONDARY)
            btn = tk.Button(
                filter_row, text=label,
                bg=BG_CARD, fg=color,
                font=FONT_SMALL, relief="flat", bd=0,
                cursor="hand2", padx=8, pady=2,
                command=lambda l=label: self._set_severity_filter(l)
            )
            btn.pack(side="left", padx=1)
            self._sev_buttons[label] = btn

        self._highlight_active_filter()

    def _build_findings_list(self, parent: tk.Frame) -> None:
        """Left pane — scrollable list of findings."""
        frame = tk.Frame(parent, bg=BG_DARK)
        frame.pack(side="left", fill="both", expand=True)

        cols = ("SEV", "TITLE", "RELATED IP", "TIME")
        col_widths = {"SEV": 80, "TITLE": 280, "RELATED IP": 140, "TIME": 80}

        self._tree = ttk.Treeview(
            frame, columns=cols, show="headings", selectmode="browse"
        )
        for col in cols:
            self._tree.heading(col, text=col,
                               command=lambda c=col: self._sort_by(c))
            self._tree.column(col, width=col_widths.get(col, 100),
                              minwidth=40, anchor="w")

        # Per-severity row tags
        for sev, color in SEVERITY_COLORS.items():
            self._tree.tag_configure(sev, foreground=color)

        self._tree.tag_configure("even", background="#161b22")
        self._tree.tag_configure("odd",  background="#1c2128")

        scroll_y = ttk.Scrollbar(frame, orient="vertical",
                                  command=self._tree.yview)
        self._tree.configure(yscrollcommand=scroll_y.set)
        scroll_y.pack(side="right", fill="y")
        self._tree.pack(fill="both", expand=True)

        self._tree.bind("<<TreeviewSelect>>", self._on_finding_selected)

        self._sort_col  = "SEV"
        self._sort_asc  = True

    def _build_detail_panel(self, parent: tk.Frame) -> None:
        """Right pane — full detail for the selected finding."""
        panel = tk.Frame(parent, bg=BG_CARD, width=400)
        panel.pack(side="right", fill="y")
        panel.pack_propagate(False)

        # Scrollable inner content
        canvas = tk.Canvas(panel, bg=BG_CARD, highlightthickness=0)
        scroll = ttk.Scrollbar(panel, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=scroll.set)
        scroll.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)

        inner = tk.Frame(canvas, bg=BG_CARD)
        win_id = canvas.create_window((0, 0), window=inner, anchor="nw")

        def on_configure(e):
            canvas.configure(scrollregion=canvas.bbox("all"))

        def on_canvas_resize(e):
            canvas.itemconfig(win_id, width=e.width)

        inner.bind("<Configure>", on_configure)
        canvas.bind("<Configure>", on_canvas_resize)

        # Bind mousewheel to canvas
        canvas.bind_all("<MouseWheel>",
                        lambda e: canvas.yview_scroll(-1 * (e.delta // 120), "units"))

        p = inner
        pad = {"padx": PAD_INNER, "pady": PAD_TINY}

        # ── Severity badge ────────────────────────────────────────────────────
        sev_frame = tk.Frame(p, bg=BG_CARD)
        sev_frame.pack(fill="x", padx=PAD_INNER, pady=(PAD_INNER, PAD_TINY))

        self._sev_label = tk.Label(
            sev_frame, text="—",
            bg=BG_CARD, fg=FG_SECONDARY,
            font=(FONT_CARD_TITLE[0], 16, "bold"), anchor="w"
        )
        self._sev_label.pack(anchor="w")

        # ── Title ─────────────────────────────────────────────────────────────
        self._title_label = tk.Label(
            p, text="Select a finding to view details",
            bg=BG_CARD, fg=FG_PRIMARY,
            font=FONT_BODY, wraplength=360,
            justify="left", anchor="w"
        )
        self._title_label.pack(fill="x", **pad)

        horizontal_separator(p, bg=BG_CARD).pack(fill="x",
                                                   padx=PAD_INNER, pady=PAD_SMALL)

        # ── Description ───────────────────────────────────────────────────────
        section_header(p, "DESCRIPTION", bg=BG_CARD).pack(fill="x", **pad)

        self._desc_label = tk.Label(
            p, text="",
            bg=BG_CARD, fg=FG_PRIMARY,
            font=FONT_SMALL, wraplength=360,
            justify="left", anchor="nw"
        )
        self._desc_label.pack(fill="x", **pad)

        horizontal_separator(p, bg=BG_CARD).pack(fill="x",
                                                   padx=PAD_INNER, pady=PAD_SMALL)

        # ── Evidence bullets ──────────────────────────────────────────────────
        section_header(p, "EVIDENCE", bg=BG_CARD).pack(fill="x", **pad)

        self._evidence_frame = tk.Frame(p, bg=BG_CARD)
        self._evidence_frame.pack(fill="x", **pad)

        horizontal_separator(p, bg=BG_CARD).pack(fill="x",
                                                   padx=PAD_INNER, pady=PAD_SMALL)

        # ── Recommendation ────────────────────────────────────────────────────
        section_header(p, "RECOMMENDATION", bg=BG_CARD).pack(fill="x", **pad)

        self._rec_label = tk.Label(
            p, text="",
            bg=BG_CARD, fg=FG_INFO,
            font=FONT_SMALL, wraplength=360,
            justify="left", anchor="nw"
        )
        self._rec_label.pack(fill="x", **pad)

        horizontal_separator(p, bg=BG_CARD).pack(fill="x",
                                                   padx=PAD_INNER, pady=PAD_SMALL)

        # ── Related context ───────────────────────────────────────────────────
        section_header(p, "RELATED", bg=BG_CARD).pack(fill="x", **pad)

        self._related_ip_label = tk.Label(
            p, text="IP: —",
            bg=BG_CARD, fg=FG_SECONDARY, font=FONT_SMALL, anchor="w"
        )
        self._related_ip_label.pack(fill="x", **pad)

        self._related_flow_label = tk.Label(
            p, text="Flow: —",
            bg=BG_CARD, fg=FG_SECONDARY, font=FONT_SMALL,
            wraplength=360, anchor="w"
        )
        self._related_flow_label.pack(fill="x", **pad)

        horizontal_separator(p, bg=BG_CARD).pack(fill="x",
                                                   padx=PAD_INNER, pady=PAD_SMALL)

        # ── Analyst note ──────────────────────────────────────────────────────
        section_header(p, "ANALYST NOTE", bg=BG_CARD).pack(fill="x", **pad)

        self._note_text = tk.Text(
            p, bg=BG_INPUT, fg=FG_PRIMARY,
            font=FONT_SMALL, height=4, wrap="word",
            relief="flat", bd=0
        )
        self._note_text.pack(fill="x", padx=PAD_INNER)

        DarkButton(p, "SAVE NOTE", command=self._save_note
                   ).pack(anchor="w", padx=PAD_INNER, pady=PAD_SMALL)

        horizontal_separator(p, bg=BG_CARD).pack(
            fill="x", padx=PAD_INNER, pady=PAD_SMALL)

        section_header(p, "FINDING STATUS", bg=BG_CARD).pack(
            fill="x", padx=PAD_INNER, pady=(0, PAD_SMALL))

        self._state_label = tk.Label(
            p, text="State: —",
            bg=BG_CARD, fg=FG_SECONDARY, font=FONT_SMALL, anchor="w")
        self._state_label.pack(fill="x", padx=PAD_INNER)

        state_btns = tk.Frame(p, bg=BG_CARD, padx=PAD_INNER)
        state_btns.pack(fill="x")

        for state_label, state_val in [
            ("INVESTIGATE", "INVESTIGATING"),
            ("CONFIRM",     "CONFIRMED"),
            ("DISMISS",     "DISMISSED"),
            ("RESOLVE",     "RESOLVED"),
        ]:
            DarkButton(
                state_btns, state_label,
                command=lambda v=state_val: self._set_finding_state(v)
            ).pack(fill="x", pady=1)

        self._selected_finding: dict | None = None
        self._selected_db_id:   int | None  = None

    # ── Analysis ──────────────────────────────────────────────────────────────

    def _run_analysis(self) -> None:
        """Execute all rules against current session data."""
        self._status_bar.set_status("Running analysis…", "active")
        self.window.update_idletasks()

        self._findings = run_all_rules(self._packets, self._flows)

        # Sort by severity (highest first by default)
        self._findings.sort(key=severity_sort_key)

        self._populate_tree()

        n = len(self._findings)
        self._status_bar.set_status(
            f"Analysis complete — {n} finding{'s' if n != 1 else ''} generated",
            "idle"
        )

    def _populate_tree(self) -> None:
        """Rebuild the findings list from self._findings."""
        self._tree.delete(*self._tree.get_children())

        active_filter = self._sev_filter.get()

        visible = [
            f for f in self._findings
            if active_filter == "ALL" or f.get("severity") == active_filter
        ]

        if not visible:
            self._tree.insert("", "end", values=(
                "—", "(no findings for this filter)", "—", "—"
            ))
            return

        for i, finding in enumerate(visible):
            sev   = finding.get("severity", "INFO")
            time_ = (finding.get("created_at") or "")[-8:]  # HH:MM:SS
            ip    = finding.get("related_ip") or "—"
            tag   = sev   # use severity as the row tag for colour

            self._tree.insert(
                "", "end", iid=str(i),
                values=(sev, finding.get("title", "—"), ip, time_),
                tags=(tag,),
            )

    def _on_finding_selected(self, event) -> None:
        """Show full detail for the clicked finding."""
        sel = self._tree.selection()
        if not sel:
            return

        active_filter = self._sev_filter.get()
        visible = [
            f for f in self._findings
            if active_filter == "ALL" or f.get("severity") == active_filter
        ]

        idx = int(sel[0])
        if idx >= len(visible):
            return

        finding = visible[idx]
        self._selected_finding = finding
        self._show_finding_detail(finding)

    def _show_finding_detail(self, finding: dict) -> None:
        """Fill the detail panel with one finding's data."""
        sev   = finding.get("severity", "INFO")
        color = SEVERITY_COLORS.get(sev, FG_SECONDARY)

        self._sev_label.configure(text=sev, fg=color)
        self._title_label.configure(text=finding.get("title", ""))
        self._desc_label.configure(text=finding.get("description", ""))
        self._rec_label.configure(text=finding.get("recommendation", ""))

        self._related_ip_label.configure(
            text=f"IP:    {finding.get('related_ip') or '—'}"
        )
        flow = (finding.get("related_flow") or "—")
        self._related_flow_label.configure(text=f"Flow:  {flow[:45]}")

        # Show current lifecycle state
        state = finding.get("state", "NEW")
        state_colors = {
            "NEW": FG_SECONDARY, "INVESTIGATING": FG_ACCENT,
            "CONFIRMED": FG_SUCCESS, "DISMISSED": FG_WARNING,
            "RESOLVED": FG_MUTED,
        }
        if hasattr(self, "_state_label"):
            self._state_label.configure(
                text=f"State: {state}",
                fg=state_colors.get(state, FG_SECONDARY))

        # Track DB id for state updates (findings saved to DB have an id)
        self._selected_db_id = finding.get("id")

        # Rebuild evidence bullets
        for w in self._evidence_frame.winfo_children():
            w.destroy()

        evidence_list = finding.get("evidence", [])
        if isinstance(evidence_list, str):
            evidence_list = [evidence_list]

        for bullet in evidence_list:
            row = tk.Frame(self._evidence_frame, bg=BG_CARD)
            row.pack(fill="x", pady=1)
            tk.Label(row, text="•", bg=BG_CARD, fg=FG_ACCENT,
                     font=FONT_SMALL).pack(side="left", padx=(0, 4))
            tk.Label(row, text=bullet, bg=BG_CARD, fg=FG_PRIMARY,
                     font=FONT_SMALL, wraplength=330,
                     justify="left", anchor="w").pack(side="left", fill="x")

        # Clear note area
        self._note_text.delete("1.0", "end")

    # ── Actions ───────────────────────────────────────────────────────────────

    def _save_note(self) -> None:
        """Attach the analyst note text to the selected finding."""
        if not self._selected_finding:
            return

        content = self._note_text.get("1.0", "end").strip()
        if not content:
            return

        target_id = (self._selected_finding.get("related_flow")
                     or self._selected_finding.get("related_ip")
                     or self._selected_finding.get("title", "finding"))

        insert_note(self.session_id, "finding", str(target_id), content)
        messagebox.showinfo("Note Saved", "Analyst note saved to session.",
                            parent=self.window)

    def _set_finding_state(self, new_state: str) -> None:
        """Update the lifecycle state of the selected finding in the DB."""
        if not self._selected_finding:
            return

        db_id = getattr(self, "_selected_db_id", None)
        if not db_id:
            messagebox.showinfo(
                "Save First",
                "Save the finding to the session first, then you can update its state.",
                parent=self.window)
            return

        note = self._note_text.get("1.0", "end").strip()
        update_finding_state(db_id, new_state, analyst_note=note)
        log_action(self.session_id, f"FINDING_{new_state}", f"id={db_id}")

        # Reflect in local dict so UI updates without reload
        self._selected_finding["state"] = new_state
        self._show_finding_detail(self._selected_finding)
        self._run_analysis()   # refresh the table

        messagebox.showinfo("Updated",
                            f"Finding marked as {new_state}.",
                            parent=self.window)

    def _save_to_session(self) -> None:
        """Persist all current findings to the session database."""
        if not self._findings:
            messagebox.showinfo("No Findings", "No findings to save.",
                                parent=self.window)
            return

        count = 0
        for finding in self._findings:
            evidence_str = "\n".join(
                finding.get("evidence", [])
                if isinstance(finding.get("evidence"), list)
                else [str(finding.get("evidence", ""))]
            )
            insert_alert(self.session_id, {
                "severity":       finding.get("severity", "INFO"),
                "title":          finding.get("title", ""),
                "description":    finding.get("description", ""),
                "evidence":       evidence_str,
                "recommendation": finding.get("recommendation", ""),
                "related_ip":     finding.get("related_ip"),
                "related_flow":   finding.get("related_flow"),
            })
            count += 1

        messagebox.showinfo("Saved",
                            f"{count} findings saved to session database.",
                            parent=self.window)

    def _export_csv(self) -> None:
        """Export all findings to a CSV file."""
        import csv
        import pathlib

        if not self._findings:
            messagebox.showinfo("No Findings", "No findings to export.",
                                parent=self.window)
            return

        path = pathlib.Path.home() / "PayloadCaptureExports"
        path.mkdir(parents=True, exist_ok=True)
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = path / f"findings_{self.session_id}_{ts}.csv"

        try:
            with open(filename, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=[
                    "severity", "title", "description",
                    "evidence", "recommendation", "related_ip",
                    "related_flow", "created_at",
                ])
                writer.writeheader()
                for finding in self._findings:
                    row = dict(finding)
                    if isinstance(row.get("evidence"), list):
                        row["evidence"] = " | ".join(row["evidence"])
                    writer.writerow({k: row.get(k, "") for k in writer.fieldnames})

            messagebox.showinfo("Exported",
                                f"Findings exported to:\n{filename}",
                                parent=self.window)
        except Exception as e:
            messagebox.showerror("Export Error", str(e), parent=self.window)

    # ── Filter / Sort ─────────────────────────────────────────────────────────

    def _set_severity_filter(self, severity: str) -> None:
        self._sev_filter.set(severity)
        self._highlight_active_filter()
        self._populate_tree()

    def _highlight_active_filter(self) -> None:
        active = self._sev_filter.get()
        for label, btn in self._sev_buttons.items():
            if label == active:
                btn.configure(bg=BG_SELECTED, fg=FG_PRIMARY)
            else:
                btn.configure(bg=BG_CARD,
                              fg=SEVERITY_COLORS.get(label, FG_SECONDARY))

    def _sort_by(self, column: str) -> None:
        if self._sort_col == column:
            self._sort_asc = not self._sort_asc
        else:
            self._sort_col = column
            self._sort_asc = True
        self._populate_tree()
